### ISSUE TITLE
Installation and packaging instructions

### ISSUE THREAD

**Issue by lockywolf** [nickbattle/vdmj#48]
Hello, and thank you for your work!

Would it be possible to add installation and packaging instructions to the README?

I know that pom-files are from Apache Maven, but I am not very sure which files exactly I need to pick up after building and where to place them. /usr/bin? /usr/lib64/java?

**Comment by nickbattle** [comment]
Thank you for the interest.

To be honest, I've not really worried about packaging because VDMJ is usually used as part of something else, like Overture or the new VSCode extension. But there is a script under src/main/scripts/vdmsl.sh. This expects the system to have been built with Maven (so "mvn clean install" at the top level). If you check the top of the script, it sets some variables that you may want to tune for your local setup, but most of the time it should "just work".

So in my personal $HOME/bin I have symlinks from "vdmsl", "vdmpp" and "vdmrt to this file:
```
lrwxrwxrwx 1 nick users  65 Nov 30 11:41 vdmpp -> /home/nick/eclipse.vdmj/vdmj-suite/vdmj/src/main/scripts/vdmsl.sh
lrwxrwxrwx 1 nick users  65 Nov 30 11:41 vdmrt -> /home/nick/eclipse.vdmj/vdmj-suite/vdmj/src/main/scripts/vdmsl.sh
lrwxrwxrwx 1 nick users  65 Nov 30 11:41 vdmsl -> /home/nick/eclipse.vdmj/vdmj-suite/vdmj/src/main/scripts/vdmsl.sh
```
Then I can execute them from anywhere. Note that the symlink name becomes the "dialect". So...
```
nick@pollux:~/FJ-VDMJ> vdmsl -i test.vdm
Parsed 1 module in 0.089 secs. No syntax errors
Type checked 1 module in 0.262 secs. No type errors
Initialized 1 module in 0.155 secs. 
Interpreter started
> p f(1)
= 2
Executed in 0.004 secs. 
> q
Bye
```

**Comment by nickbattle** [comment]
But to answer your point(!), yes I should probably say something about this in the README!

**Comment by nickbattle** [comment]
I've added some more words to the vdmj README as follows. Is there anything more you would like to see?

[README](https://github.com/nickbattle/vdmj/files/6324165/README.txt)

**Comment by lockywolf** [comment]
Well, my intention was to use it as a command-line tool as described here: https://github.com/peterwvj/vdm-mode

I have looked a bit at the way Java applications are usually installed system-wide in Linux, and that is usually having a directory under `/opt`, for example `/opt/vdmj`, where the main body of files and libraries would be installed, as well as a shell-script in `/bin` and documentation in `/usr/doc`? 

I guess, asking you to provide such way of installing would be too much, so I guess, I have no more questions. 
The issue can be closed, thank you.

**Comment by nickbattle** [comment]
It would be possible to do that - for example to package the jars and scripts into a RPM format file and adding that to a local repository. But as I said (and as the EMACs example illustrates), VDMJ is usually packaged with something else, which handles its own packaging. So I'll leave it as it is, unless I get a lot more requests for this.
