### ISSUE TITLE
Allow type checking lambdas as total functions

### ISSUE THREAD

**Issue by donbex** [nickbattle/vdmj#55]
When using the VDMJ language server, either in VSCode or neovim, I'm seeing lots of type checking errors where lambdas are used where total functions are expected. Interestingly Overture does not raise these errors, although the fact that for unrelated reasons I am currently stuck with version 2.6.4 might have something to do with it.

The most obvious fix would be to set the `partial` parameter to `false in
https://github.com/nickbattle/vdmj/blob/9ce741ce37b284984c9c6fbce190f169739897f0/vdmj/src/main/java/com/fujitsu/vdmj/tc/expressions/TCLambdaExpression.java#L97

However, I can see arguments both for and against this change:
- _For_: lambdas don't carry pre and post conditions; as such, they cannot impose restrictions on their domain, so the safest thing to do is assume (and require) lambdas to be total functions, because we don't have enough information to conclude otherwise.
- _Against_: someone might prefer to mark as total only functions that have been explicitly proven to be total, and assume every other function to be partial; since lambdas cannot carry this mark, they must then be considered partial functions.

-----

If you disagree with the above change, would it be possible at least to add a parameter to the `Properties` class to this effect? That is, assuming that the language server can read settings from a `vdmj.properties` file, which I have so far been unable to do.

**Comment by nickbattle** [comment]
I'm testing with Overture 3.0.2, which still doesn't show the error, but I do get it with VDMJ/VSCode. This may be a test that has been missed in Overture - there were some recent changes for total functions and proof obligations.

This kind of change is really something that should be put to the Language Board. The tool change you suggest would probably do what you want, but there may be wider ramifications for the change that we ought to consider. Unfortunately the Language Board process is quite slow. Is this causing significant trouble?

I can try asking some of the team why lambdas are partial; there might be a good reason :-)

**Comment by donbex** [comment]
> Is this causing significant trouble?

The errors are preventing me from using the debugger through the language sever, and treating those functions as partial would require extensive changes to our specification. I wouldn't consider this as "significant trouble", however, because I am currently the only one in my team using the language server and I can patch VDMJ locally while awaiting a decision.

> I can try asking some of the team why lambdas are partial; there might be a good reason :-)

That would be great, thank you. Given a good enough reason, we might decide to change our specification sooner rather than later...

**Comment by nickbattle** [comment]
I've just pushed a small change to the Overture code to bring it in line with VDMJ. The particular check for the compatibility of +> and -> functions was missing. It should get swept up with the next bugfix release.

I also asked PGL about the history of partial lambda's and whether it might cause a problem to change it. He couldn't recall any particular history and didn't immediately see a semantic problem with changing it (though to be fair, he's on holiday and perhaps didn't have a lot of time!). The right way to proceed with this, if you want to, is to raise a Request for Modification with the Language Board. Then we can consider it in more detail.

See [this guide](https://github.com/overturetool/language/wiki) to the community process for that.

I think we should close this issue, since VDMJ is behaving as expected and an Overture change has been made.

**Comment by donbex** [comment]
Sounds good to me. In the coming days I will discuss this with my teammates and decide on the immediate course of action.
