### ISSUE TITLE
Proof obligation generator fails for local curried functions

### ISSUE THREAD

**Issue by csb6** [nickbattle/vdmj#73]
Software version: VDMJ v4.5.0 (I am using v1.3.7 of the VDM VSCode extension)

I have been encountering a POG issue that seems to be similar to #67. When defining a local curried function such as:

```
f: int -> int -> int
f(a)(b) == let
    g: int -> int -> int
    g(-)(d) == d
in g(a)(b);
```

the proof obligation generator emits an error message (I removed the module name/path and the line numbers for brevity):

```
f: function apply obligation in <module-name> (<path-to-file>) at line <line number>
(forall a:int, b:int &
  (let g: (int -> (int -> int)) g(-)(d) == d in
    pre_(g(a), b)))

Function type is not a -> or +> function
```

When the local curried function is recursive, such as:

```
h: int -> int -> int
h(a)(b) == let
    i: int -> int -> int
    i(c)(d) == i(c)(d)
in i(a)(b)
```

then the proof obligation generator emits these error messages:

```
h; i: function apply obligation in <module-name> (<path-to-file>) at line <line number>
(forall a:int, b:int &
  (forall c:int, d:int &
    pre_(i(c), d)))

Error 3182: Name 'i' is not in scope in <module-name> (console) at line <line number>
PO has type errors?
h: function apply obligation in <module-name> (<path-to-file>) at line <line number>
(forall a:int, b:int &
  (let i: (int -> (int -> int)) i(c)(d) == i(c)(d) in
    pre_(i(a), b)))

Error 3182: Name 'i' is not in scope in <module-name> (console) at line <line number>
Function type is not a -> or +> function
```

**Comment by nickbattle** [comment]
Thanks for reporting this and giving clear examples.

I've tried the f and h functions in the latest version (4.6.0-SNAPSHOT) and they generate POs cleanly (here via the VDMJ command line):
```
> pog
Generated 3 proof obligations:

Proof Obligation 1: (Unproved)
f: function apply obligation in 'DEFAULT' (test.vdmsl) at line 6:8
(forall a:int, b:int &
  (let g: int -> (int -> int) g(-)(d) == d in
    pre_(g(a), b)))

Proof Obligation 2: (Unproved)
h; i: function apply obligation in 'DEFAULT' (test.vdmsl) at line 11:16
(forall a:int, b:int &
  (let i: int -> (int -> int) i(c)(d) == i(c)(d) in
    (forall c:int, d:int &
      pre_(i(c), d))))

Proof Obligation 3: (Unproved)
h: function apply obligation in 'DEFAULT' (test.vdmsl) at line 12:8
(forall a:int, b:int &
  (let i: int -> (int -> int) i(c)(d) == i(c)(d) in
    pre_(i(a), b)))
```

We've been doing a lot of work on the POG recently because of the QuickCheck plugin (lightweight PO verification). It's possible that these problems were cleaned up along the way.

Would you be able to try the 4.6.0-SNAPSHOT? (all branches on GitHub should be at the same version, because we're preparing for a release). If not, we're preparing release candidates for VDM-VSCode 1.4.0, which will include the 4.6.0 release. We hope to have this out in August sometime.

**Comment by nickbattle** [comment]
I've uploaded two 240818 distribution ZIPs for 4.6.0-SNAPSHOT in the release area. That will allow command line testing, at least.

**Comment by csb6** [comment]
I just tried out the VDM VSCode snapshot, and as you found there are no longer any error messages from the PO generation. Thanks for your help!
